// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOD38pzCVVwt6fuqSJSJOyL6kPNDyjS2g',
    appId: '1:781052311292:android:3cc1796f149d9b04264979',
    messagingSenderId: '781052311292',
    projectId: 'daily-dating-app',
    storageBucket: 'daily-dating-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6D3TTiQlIljxTbVZNJwmYEgefZF6Heck',
    appId: '1:781052311292:ios:6fdfb01344985a3c264979',
    messagingSenderId: '781052311292',
    projectId: 'daily-dating-app',
    storageBucket: 'daily-dating-app.firebasestorage.app',
    iosBundleId: 'com.example.appIncontri',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU4t2vSi7fv9T3J3iUB2cylopQ5GONwrA',
    appId: '1:781052311292:web:4e9ed36cc12836f6264979',
    messagingSenderId: '781052311292',
    projectId: 'daily-dating-app',
    authDomain: 'daily-dating-app.firebaseapp.com',
    storageBucket: 'daily-dating-app.firebasestorage.app',
  );
}
